#define CLAWKP 0.1
#define CLAWKI 0.1
#define CLAWKIMAX 0.3
#define ALLOWABLE_ERROR_CLAW 1
#define CLAWMAX_SPEED 0.8
#define CLAWMAX_ACCELERATION 5

#define WRISTFF 0
#define WRISTKP 0.4
#define WRISTKI 0
#define WRISTKIMAX 0.1
#define ALLOWABLE_ERROR_WRIST 0.05  
#define WRISTMAX_SPEED 0.5
#define WRISTMAX_ACCELERATION 3