#define KP 0.15
#define KI 0
#define KIMAX 0.1
#define ALLOWABLE_ERROR_CLAW 0.3
#define MAX_SPEED 0.2
#define MAX_ACCELERATION 1

#define WRISTKP 0.15
#define WRISTKI 0
#define WRISTKIMAX 0.1
#define ALLOWABLE_ERROR_WRIST 0.3
#define WRISTMAX_SPEED 0.2
#define WRISTMAX_ACCELERATION 1