#define KP 0.14
#define KI 0
#define KIMAX 0.1
#define ALLOWABLE_ERROR_CLAW 0.5
#define MAX_SPEED 0.7
#define MAX_ACCELERATION 5

#define WRISTKP 1
#define WRISTKI 0
#define WRISTKIMAX 0.1
#define ALLOWABLE_ERROR_WRIST 0.2   
#define WRISTMAX_SPEED 1.0
#define WRISTMAX_ACCELERATION 4